### ISSUE TITLE
Sending multiple items to AFAS via REST

### ISSUE THREAD

**Issue by woutervandamme** [rmuit/PracticalAfas#2]
In the readme. it says that you don't know how to send multiple items to afas (for an order), here is an example json that send multiple items to AFAS. 

{
                      "FbSales": {
                        "Element": {
                          "Fields": {
                            "DbId" : "xxxxxxxxxxx",
                            "Unit" : "1",
                            "War": "*****",
                          },
                          "Objects": {
                            "FbSalesLines": {
                              "Element": [{"Fields": {
                                "VaIt": "Art",
                                "ItCd": "xxxxx",
                                "BiUn": "stk",
                                "QuUn": "5"
                              }},{"Fields": {
                                "VaIt": "Art",
                                "ItCd": "xxxxxx-xxx",
                                "BiUn": "stk",
                                "QuUn": "5"
                              }},]
                            }
                          }
                        }
                      }
                    }

Thank you for creating this package , it has saved me lots time.

**Comment by rmuit** [comment]
Thank you! I have included this possibility in a new release. (Meaning: Helper::normalizeDataToSend() does not throw an exception anymore, while parsing input with multiple elements.)

For completeness:
What I see in your example is that an 'Element' value can be an array containing multiple objects.
(In AFAS docs, I've only seen examples of 'Element' containing one single objects.)
I will assume that both a single object and an array of objects can be used _for every 'Element' value_, in any object. Even though I don't officially know whether that's true.

(I still have not tested updates over REST myself, but this has given me enough information to overhaul my Helper code, so that the same code is now used for building arrays for the REST API, and XML strings for the SOAP API. After this rewrite, and doing lots of compatibility tests on my older code/XML... I see a possibility for a rewrite of the UpdateConnector/validation related parts. We'll see if I get to do that soon.)

**Comment by rmuit** [comment]
Actually no... On second thought, I think I can and should start out with stricter validation, and uniform output:
* Some outer' objects _must never_ have multiple embedded objects of the same kind (like KnPerson inside KnContact)
* Other 'outer' objects are allowed to have multiple embedded objects, and then my library should _accept_ both a single object and an array of objects, but _output_ always an array.

(And then I'll just hear if there are any misassumptions there. I'll default to the second case for things I don't know for sure, like e.g. KnContact inside KnOrganisation.)

**Comment by rmuit** [comment]
The rewrite of the UpdateConnector/validation related parts has happened. I still need to write additional tests and documentation before tagging a 2.0 release.
