### ISSUE TITLE
Get all records in Rest Call from Afas

### ISSUE THREAD

**Issue by anujeetphj** [rmuit/PracticalAfas#3]
I want to get all records at once that are in Afas using REST Client, but when no parameters like 'take' or 'skip', it gives me 100 records only. Isn't there any way to get all records at once?

**Comment by rmuit** [comment]
No.
Sorry, that's a REST limitation on the server end (not my library), so there is no way. I tested.

Many (most?) API endpoints make restrictions like this... I guess to prevent timeouts.

You can check if Helper::getDataBatch() works for you. I think you can call that repeatedly. I wrote it to get complete data sets. (Even though my use case was explicitly to fetch different batches at different times, so it may be a bit more complicated than you need. But I hope I have documented it properly.)

**Comment by anujeetphj** [comment]
What if I just use callAfas in RestCurlClient again and again like
take = 100
take = 100 skip = 100
take = 100 skip = 200
so on...

Can this tell me when I am done fetching all?

**Comment by rmuit** [comment]
Sure. Just count the number of items returned, and check if it's smaller than 100.

I don't like using skip to get full data sets though. It can be good for 'human' display of paging, but it could (depending on your connector) skip records - or return duplicate records in multiple queries, if data changes while you are querying.

That's why I'd recommend sorting on a unique field, and then doing a filter on (field > highest-value-you-got-last-time), plus take = 100.

If you call Helper::getDataBatch() repeatedly with the appropriate values, it does that for you.

**Comment by RvdE** [comment]
If you use skip=-1 and take=-1 it will return all records. This works for both SOAP and REST interfaces of AFAS.

**Comment by rmuit** [comment]
Thanks for that! I had no idea.

I just tested this and it turns out that
* my client classes do not support this because -1 is considered invalid
* specifying skip=-1 is enough, (It will cause the 'take' argument to not be used, and even not be validated at all.)

The first point is fixed in master. A version 2.1 will be tagged within a few weeks (that should contain only minor changes, some extra tests and an updated README).

Admittedly it would have been better if I had done this _before_ trying to finish my 2.0 rewrite. But anyway...
