### ISSUE TITLE
Endpoint url is hardcoded, should be configurable

### ISSUE THREAD

**Issue by vazaha-nl** [rmuit/PracticalAfas#4]
The end point url has changed from .afasonlineconnector.nl to .rest.afas.online. Old host doesn't work anymore, it gives a 401 error (at least for me) but this url is hardcoded in practicalafas/src/RestCurlClient.php:253 so I have to edit the source to make it work. This option should be configurable, with a default.

**Comment by rmuit** [comment]
Thanks. I rely on other people for these things, because I do not actively use AFAS at the moment, so I am not exposed to these changes. (I am open to a little AFAS back-end programmer / data analyst work changing that, so I can test my own stuff and keep everyone happy with updated code ;-) )

(This despite the fact that I've pushed a significant rewrite of the update connector / Helper code last night, by the way. >90% done but Connection::sendData() is broken for non-string $data at the moment. And I see I broke composer.json.)

Should it be configurable, though?
https://kb.afas.nl/index.php/details/kb/?0100000093460010129720160202 suggests that AFAS' current practice is to just change the URL endpoint and phase the old one out later - but at the moment the new endpoint is operational, everyone can use it. So we can still hardcode it.

What we should do is set CURLOPT_SSLVERSION to CURL_SSLVERSION_TLSv1_2, though. (It's not totally backward compatible and could start generating errors for really old php/curl versions but this is the appropriate time for that. Also I'll need to re-check if/how it's possible to pass this as an option i SoapAppClient.)

I'll make sure this is in the upcoming v2.0 version. Maybe @doozycode is working on it, because shortly after your message a PR was opened - and closed again.

**Comment by vazaha-nl** [comment]
Thanks! Do you have any forecast when the 2.0 version will be available?

**Comment by rmuit** [comment]
It's all evening/weekend volunteer work so estimates are unreliable.

It should be done "soon", which I think translates to ~2 weeks. I just want to finish writing unit tests for code already written, and write docs, plus do the above, before cutting a 2.0 tag. Master already has the rewrite, featuring
* Connection & client classes are the same, except Connection::sendData() will work a bit differently and the client classes have moved to a sub-namespace
* UpdateObject & related has more extensible code for sending data. The class has plenty of comments.

**Comment by rmuit** [comment]
Well. 2 weeks turned into 8 weeks. I got carried away and kept fixing up the UpdateObject classes further.

I'm still not done yet, so no 2.0 tag yet. but should be fixing some AFAS stuff myself this week, so the changes to the endpoint URL are in. (My last 2 commits are not tested yet! Will do in a few days.)

**Comment by rmuit** [comment]
2.0 was released this week.
